In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../data/raw_players.csv")

In [4]:
df.head()

,player_id,player_name,age,nationality,club,position,overall_rating,potential_rating,matches_played,goals,assists,minutes_played,market_value_million_eur,contract_years_left,injury_prone,transfer_risk_level
0,1,Player_1,23,Germany,Liverpool,ST,65,87,8,6,14,2976,122.51,3,No,Low
1,2,Player_2,36,England,FC Barcelona,ST,90,76,19,3,18,2609,88.47,5,No,High
2,3,Player_3,31,France,Juventus,RB,75,91,34,12,15,1158,20.24,3,No,Medium
3,4,Player_4,27,Portugal,Manchester City,LW,90,86,35,18,13,145,164.29,0,Yes,Medium
4,5,Player_5,24,Brazil,Liverpool,CDM,84,96,41,6,6,2226,121.34,4,No,Low

In [6]:
df.shape

(2800, 16)

In [7]:
df.columns

Index(['player_id', 'player_name', 'age', 'nationality', 'club', 'position',
       'overall_rating', 'potential_rating', 'matches_played', 'goals',
       'assists', 'minutes_played', 'market_value_million_eur',
       'contract_years_left', 'injury_prone', 'transfer_risk_level'],
      dtype='str')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2800 entries, 0 to 2799
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   player_id                 2800 non-null   int64
 1   player_name               2800 non-null   str
 2   age                       2800 non-null   int64
 3   nationality               2800 non-null   str
 4   club                      2800 non-null   str
 5   position                  2800 non-null   str
 6   overall_rating            2800 non-null   int64
 7   potential_rating          2800 non-null   int64
 8   matches_played            2800 non-null   int64
 9   goals                     2800 non-null   int64
 10  assists                   2800 non-null   int64
 11  minutes_played            2800 non-null   int64
 12  market_value_million_eur  2800 non-null   float64
 13  contract_years_left       2800 non-null   int64
 14  injury_prone              2800 non-null   str
 15  transfer_risk_level       2800 non-null   str
dtypes: float64(1), int64(9), str(6)
memory usage: 350.1 KB

In [9]:
df.isnull().sum()

player_id                   0
player_name                 0
age                         0
nationality                 0
club                        0
position                    0
overall_rating              0
potential_rating            0
matches_played              0
goals                       0
assists                     0
minutes_played              0
market_value_million_eur    0
contract_years_left         0
injury_prone                0
transfer_risk_level         0
dtype: int64

In [10]:
df["position"].unique()

<StringArray>
['ST', 'RB', 'LW', 'CDM', 'CM', 'GK', 'LB', 'RW', 'CB']
Length: 9, dtype: str

In [11]:
df["club"].unique()

<StringArray>
[      'Liverpool',    'FC Barcelona',        'Juventus', 'Manchester City',
   'Bayern Munich',             'PSG',     'Real Madrid']
Length: 7, dtype: str

In [12]:
df.describe()

,player_id,age,overall_rating,potential_rating,matches_played,goals,assists,minutes_played,market_value_million_eur,contract_years_left
count,2800.000000,2800.000000,2800.000000,2800.000000,2800.000000,2800.000000,2800.000000,2800.000000,2800.000000,2800.000000
mean,1400.500000,27.952500,76.866786,81.563929,27.135714,19.261786,12.015000,2250.101429,90.565500,2.527857
std,808.434702,6.750192,9.921113,9.755799,15.979627,11.567858,7.188459,1295.461829,52.078881,1.699445
min,1.000000,17.000000,60.000000,65.000000,0.000000,0.000000,0.000000,0.000000,0.670000,0.000000
25%,700.750000,22.000000,68.000000,73.000000,13.750000,9.000000,6.000000,1131.250000,45.355000,1.000000
50%,1400.500000,28.000000,77.000000,82.000000,27.000000,19.000000,12.000000,2251.000000,89.170000,3.000000
75%,2100.250000,34.000000,85.000000,90.000000,41.000000,30.000000,18.000000,3366.250000,136.682500,4.000000
max,2800.000000,39.000000,94.000000,98.000000,54.000000,39.000000,24.000000,4497.000000,179.960000,5.000000

In [13]:
df.sample(10)

,player_id,player_name,age,nationality,club,position,overall_rating,potential_rating,matches_played,goals,assists,minutes_played,market_value_million_eur,contract_years_left,injury_prone,transfer_risk_level
1798,1799,Player_1799,17,Spain,FC Barcelona,RW,84,98,41,8,7,1419,33.10,1,No,Low
1966,1967,Player_1967,27,Germany,Bayern Munich,LB,82,96,52,30,14,3667,14.04,4,No,High
2497,2498,Player_2498,21,Portugal,Juventus,GK,90,97,14,27,3,459,142.33,1,No,Medium
1323,1324,Player_1324,21,Germany,Manchester City,CM,82,65,6,20,6,1515,24.70,4,Yes,Medium
1282,1283,Player_1283,18,Portugal,PSG,CM,88,81,23,35,19,1552,15.90,5,No,Low
811,812,Player_812,27,Portugal,Real Madrid,CM,75,96,44,33,15,3177,166.43,5,Yes,Low
2183,2184,Player_2184,23,Netherlands,PSG,ST,90,78,9,7,7,3672,79.17,4,No,Medium
2445,2446,Player_2446,18,Argentina,Manchester City,CDM,73,67,36,36,9,2619,10.91,4,Yes,Low
61,62,Player_62,20,England,FC Barcelona,GK,85,79,50,26,0,1015,77.88,5,No,Low
1928,1929,Player_1929,21,Germany,Bayern Munich,LW,78,94,42,35,17,461,26.76,1,No,Low

**Column Types**

*Numerical Columns*
age
overall_rating
potential_rating
matches_played
goal
assists
minutes_played
market_value_million_eur
contract_years_left

*Categorical Columns*
player_name
nationality
club
position
injury_prone
transfer_risk_level

**Data Cleaning**

*Data Type Validation*
The numerical columns identified above -> numeric values, no strings

---

*Range Validation*

Players stats need to be within realistic ranges for pro football
- age between 16 and 45
- overall_rating between 0 and 100
- potential_rating between 0 and 100
- goals >= 0
- assists >= 0
- matches_played >= 0
- minutes_played >= 0
- market_value_millino_eur >= 0

Violating rows checked or removed

---

*Categorical Columns*

May have inconsistent formatting or whitespace

- removed leading/trailing whitepace
- consistent capitalization
- validating position labels

---

*Logical Checks*

- Players with 0 matches played should have 0 goals and assists
- Players with very low minutes played shouldn' have unusually high goals or assists
- Minutes played sould correlate with the matches played

---

*Duplicate Records*

Each player should appear only once.
Checed using player_id column, duplicates removed.

---

*Final Clean Dataset*

Saved as: data/clean_players.csv

In [15]:
import pandas as pd
df = pd.read_csv("../data/features_players.csv")
print(df.columns)

Index(['player_id', 'player_name', 'age', 'nationality', 'club', 'position',
       'overall_rating', 'potential_rating', 'matches_played', 'goals',
       'assists', 'minutes_played', 'market_value_million_eur',
       'contract_years_left', 'injury_prone', 'transfer_risk_level',
       'position_group', 'goal_contribution', 'performance_score', 'age_group',
       'experienced'],
      dtype='str')